server:
  port: 8989
spring:
  jpa:
    hibernate:
      ddl-auto: create    # DO NOT USE THIS IN PRODUCTION
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test

